### ISSUE TITLE
The stub implementations of a protocol are treated as testable code

### ISSUE THREAD

**Issue by decorator-factory** [coveragepy/coveragepy#1055]
**Describe the bug**
`coverage.py` is reporting the stub implementations (`...`) of methods in a protocol as red, when in reality they're not real methods that should be executed

**To Reproduce**
The issue can be reproduced by running `coverage` with this file:
```py
# protocol_bug.py
from typing import Protocol

class MyProtocol(Protocol):
    def foo(self: int) -> str:
        ...

print("Hello, world!")
```
```bash
$ python -m coverage run protocol_bug.py && python -m coverage html
```
the `...` line is reported "red' (not ran).

**Expected behavior**
I think it would make more sense for protocol definitions to be ignored

**Comment by decorator-factory** [comment]
Fixed with a regular expression filter, no worries :+1:

**Comment by nedbat** [comment]
@decorator-factory Do you mind sharing the specific regex and setting that worked for you?

**Comment by decorator-factory** [comment]
This worked for me:
```regex
class \w+\((.*?, )?(t(yping)?\.)?Protocol(, (t(yping)?\.)?Generic\[.*?\])?\):
```
it doesn't account for edge cases like awkward spacing, multiline parents lists etc., but should cover all usual protocols, including generic ones.

**Comment by nedbat** [comment]
I added a simpler example to the docs in 551949f426b8ef292df5e6d4caf9d9d038a92634:
```
class .*\bProtocol\):
```

**Comment by peterschutt** [comment]
FYI for those who come across it, for `pyproject.toml` config I needed to double escape, e.g., `"class .*\\bProtocol\\):"`.

**Comment by knyghty** [comment]
@nedbat do you think these could be excluded automatically? I don't there's any case where a protocol method would be run.

One (minor) issue with the approach here is that it excludes the entire class, but I think only the method bodies need to be excluded.

**Comment by nedbat** [comment]
@knyghty can you show a short example of where you don't want to exclude the entire class?

**Comment by knyghty** [comment]
@nedbat I'll admit that my wish to not exclude it is mostly for the sake of "completion". It is nice not to have to exclude a whole class if you just want to exclude the method. It's just feels nicer to only exclude the minimum amount possible.

I realise this is probably not _extremely_ useful, other than perhaps not having to add this into the config if you're going to be using `Protocol` at all.

Since you asked for an example:

```python
class Callback(Protocol):
    some_attribute: str

    def __call__(
        self, message: str, device_id: str, **kwargs: object
    ) -> None:
        ...
```

Here, as long as it's imported, the class is covered, including the attribute, only the method body is not covered (the `...`).

Right now the only options are adding the pragma to every `Protocol` method, or to add every entire `Protocol` class to `exclude_lines`, neither of which seem really ideal.
