### ISSUE TITLE
Add config option to append data during run.

### ISSUE THREAD

**Issue by nedbat** [coveragepy/coveragepy#110]
Is there a way to set a flag in the .coveragerc file so that the data previously collected will not be erased when my program starts with coverage (similar to the –a flag in the run command)?

Thanks,

Orly Peck.

----------------------------------------
- Bitbucket: https://bitbucket.org/ned/coveragepy/issue/110

**Comment by nedbat** [comment]
I'm not sure this would be useful, and can be accomplished with the --append flag on the run command.

**Comment by cwalther** [comment]
I would like to reopen this request: In my case, I cannot pass `--append` on the command line, because there is no command line. I am working on an embedded Python interpreter inside a larger C++ application and therefore cannot start coverage measurement using `coverage run`. Instead, I use `coverage.process_startup()` in _sitecustomize.py_, so my only way of passing options in is the configuration file.

It also seems inconsistent that some options can be set both on the command line and in the configuration file, but `--append` cannot.

I took a quick look at the source code and it looks like this wouldn’t be totally straightforward to add because `--append` is implemented totally outside of configuration handling, so I didn’t just do it.

It’s not a showstopper though, I can probably get by with moving data files aside and combining them later, or by reimplementing `process_startup()` to do what I want, but it would be more convenient to have this built in.

**Comment by nedbat** [comment]
@cwalther You are in a very specialized situation.  Just reading `append` from the config file wouldn't solve your problem, we'd also have to handle that setting in `process_startup()`.  Since that function is mostly for use by subprocesses, it would often be the wrong thing to do, because it could mean multiple subprocess all trying to add data to the same data file.  That might work, but it's not how it's been used so far, so we'd also have to add and test some concurrency guarantees in the database code.

I think your ideas of managing multiple files, or writing your own `process_startup` analog are for the best.

**Comment by cwalther** [comment]
Ah, good point. Yes, I’m misusing the startup function for subprocesses – I guess there would need to be a separate one for embedded interpreters (along with an official way of installing the tracing function on threads created from the C++ side (https://github.com/nedbat/coveragepy/issues/686#issuecomment-631760644)).

Considering that coverage.py doesn’t seem to be designed for this use case at all, it’s working amazingly well!
