### ISSUE TITLE
Safety check release bug

### ISSUE THREAD

**Issue by dokazhi** [coveragepy/coveragepy#1200]
**Describe the bug**
Safety check says 6.0b1 is more secure version
![image](https://user-images.githubusercontent.com/24829504/127864804-66572f8e-8df6-4f3f-bcc6-3f3d43e9dc76.png)

**To Reproduce**
How can we reproduce the problem?  Please *be specific*. Don't just link to a failing CI job. Answer the questions below:
1. What version of Python are you using?
1. What version of coverage.py are you using? The output of `coverage debug sys` is helpful.
1. What versions of what packages do you have installed? The output of `pip freeze` is helpful.
1. What code are you running?  Give us a specific commit of a specific repo that we can check out.
1. What commands did you run?

**Expected behavior**

**Additional context**

**Comment by danuker** [comment]
As you can see, [version 6.0b1](https://github.com/nedbat/coveragepy/releases) is the latest released right now, so if you want `security` to stop complaining, you should perhaps update.

Alternatively, you can ignore this issue with `-i 41002` as arguments for `safety`, if your organization does not see coverage using MD5 as a risk (which I doubt it does, unless you need to be blindly FIPS compliant like [the guy that asked for this change here](https://github.com/nedbat/coveragepy/issues/1189)).

Personally, I think this is a bug in `safety`, because I don't see how the coverage tool could be tricked with a hash collision into exploiting any system.
Edit: it seems [somebody else agrees.](https://github.com/pyupio/safety-db/issues/2335)

**Comment by nedbat** [comment]
This is a duplicate of #1198.
