### ISSUE TITLE
Coverage report is incorrect if package-under-test is imported prior to invocation

### ISSUE THREAD

**Issue by LachlanMarnham** [coveragepy/coveragepy#1311]
# Describe the bug
When executing `coverage.cmdline.main(...)` from within code, the coverage report is sensitive to whether the package under test has been imported. Note: this may be expected behaviour and not a bug, so if it is expected and there is any workaround I would really appreciate any advice.

# To Reproduce
`python==3.7.5.`
`coverage==6.2`
`pytest==6.2.5`

### Minimal working example:
If I run:
```
coverage run --source my_package -m pytest
```
the coverage reported is 92%. If I run the following code:
```python
from coverage.cmdline import main

main(['run', '--source', 'my_package', '-m', 'pytest'])
```
the coverage reported is 92% again. However, if I import something from `my_package` prior to the
call to `main`:
```python
from coverage.cmdline import main
from my_package import MyClass, my_function

main(['run', '--source', 'my_package', '-m', 'pytest'])
```
the coverage drops to 50%.

## Expected behavior
From the docs:
```
It monitors your program, noting which parts of the code have been executed, then analyzes the source to identify code that could have been executed but was not.
```
In this case, the program being executed it `pytest`, and I would expect the invocation of `coverage` to report on which parts of the code were executed by `pytest`. **Am I wrong to expect this behaviour? And, if so, is there a workaround? **

**Comment by nedbat** [comment]
Hi, sorry I've let this sit so long.  This behavior is expected. Coverage can only measure execution of code after it has been started.  When you import a module, the top-level statements are executed. If you import it before starting coverage, then coverage can't measure that execution.

You haven't mentioned which lines are missing when you pre-import, but I think they will be the import/class/def lines in your modules.

I'm not sure what the options are for a workaround, because I don't know why you are using coverage programmatically like this, rather than the simpler approach of using it as a command to run your program.  Let's talk about what you need to do, and we'll find a solution.

(BTW, I didn't intend cmdline.main to be a supported interface.)
