### ISSUE TITLE
coverage report raise NoDataError("No data to report.")

### ISSUE THREAD

**Issue by lvyansheshou** [coveragepy/coveragepy#1437]
Hi, The environment is Python 3.8.5 coverage py, version 6.4.4 x86_ 64 using the coverage API, report no data to report However, using the command line, print the report normally
![image](https://user-images.githubusercontent.com/26155625/185116641-4e278a85-de0a-4740-b981-5e12ed59f8b8.png)
![image](https://user-images.githubusercontent.com/26155625/185116693-dc2f59d1-c9ff-4ccb-ac2f-b4c1fd47d9c3.png)

Can you help me？

**Comment by nedbat** [comment]
You say you are using the API, which means you have written some code to use the API.  You should share that code, and the command line you used that worked.  Ideally, you'd have a link to the complete project so that we can find other details we need.  Lastly, it's easier to help if you copy text and paste it as text rather than pasting screenshots.
