### ISSUE TITLE
Override path in sources/source in XML Report

### ISSUE THREAD

**Issue by pinguin999** [coveragepy/coveragepy#1568]
Our CI System needs the path in sources/source to match the Repo structure. 
We run out tests in a different location. So we need to change the path in the generated coverage.xml file

Our current solution is to run `sed --in-place 's,<source>/a/b</source>,<source>/x/y/</source>,' coverage.xml` to replace it after generation.

**Describe the solution you'd like**
There is a parameter or config value to hard code the path in sources/source.

**Describe alternatives you've considered**
I can continue to run after the generation.
`sed --in-place 's,<source>/a/b</source>,<source>/x/y/</source>,' coverage.xml`

**Comment by nedbat** [comment]
The [[paths] setting](https://coverage.readthedocs.io/en/7.2.1/config.html#paths) can be used to remap data measured in one location to another location.  Typically this is because a test suite is run in a few different environments, then all the data files are collected together and combined.  The combine step uses the \[paths] setting to remap the measured data so that it conforms to the layout of the combining environment.

If you are not using `coverage combine`, you can add it as a step to get this remapping.  

Does that help? It might be that I still don't understand your situation.  Why do you have different layouts?
