### ISSUE TITLE
Incorrect report on `elif` or `case` branch

### ISSUE THREAD

**Issue by alexei** [coveragepy/coveragepy#1670]
**Describe the bug**

I have a situation where coverage is reporting incorrectly (by my expectations) on `elif` and `case` branches. I may be missing something, so I figured I should ask.

**To Reproduce**

I think the example is self-explanatory:

```python
def f1(i: int) -> int:
    if i % 2:
        return 1
    else:
        return 2


def f2(i: int) -> int:
    if i % 2:
        return 1
    if i % 2 == 0:  # line 11 didn't return from function 'f2', because the condition on line 11 was never false
        return 2


def f3(i: int) -> int:
    if i % 2:
        return 1
    elif i % 2 == 0:  # line 18 didn't return from function 'f3', because the condition on line 18 was never false
        return 2


def f4(i: int) -> int:
    match i % 2:
        case 1:
            return 1
        case 0:  # line 26 didn't return from function 'f4', because the pattern on line 26 never matched
            return 2


def test_f1() -> None:
    assert f1(1) == 1
    assert f1(2) == 2


def test_f2() -> None:
    assert f2(1) == 1
    assert f2(2) == 2


def test_f3() -> None:
    assert f3(1) == 1
    assert f3(2) == 2


def test_f4() -> None:
    assert f4(1) == 1
    assert f4(2) == 2
```

**Expected behavior**

To be honest I was expecting 100% but I'm getting 91.18%.

**Additional context**

FWIW I'm running pytest 7.4.0, cov 4.1.0 and coverage.py 7.2.7 on Python 3.11.

**Comment by nedbat** [comment]
There is a branch on line 11, the true case and the false case.  As the annotation explains, the condition was never false.  So you are missing a possible branch, and coverage correctly tells you that.  It's working as expected.

You understand why the branch is missing (because the condition on line 9 is true in that case, and the function ends earlier).  But coverage.py can't understand that.

You should write the function like f1 instead of like f2, f3, or f4.

**Comment by alexei** [comment]
Got it, thanks for the response
