### ISSUE TITLE
How to only show functions that hasn't been covered?

### ISSUE THREAD

**Issue by mrajancsr** [coveragepy/coveragepy#1750]
**Describe the bug**
Currently code coverage shows coverage based on statements.  This seems inaccurate in a larger scheme of things.  If a function hasn't been tested, it should show the entire function as uncovered. Rather than showing def statements as being covered and return statements as being uncovered.  

**To Reproduce**
Simple.py

def multiply(x,y):
    return x*y

def add(x,y):
    return x + y

def subtract(x,y):
    return x-y

def divide(x,y):
    return x/y

test_simple.py

from Simple import multiply

def test_multiply():
    assert 3*4 == multiply(3,4)

then I go to the terminal and type 
pytest test_simple.py --cov=Simple

It's showing 5/8 = 62% covered rather than 25% covered.  Is there anyway I can show the desired coverage?  
How can we reproduce the problem? 
See above 
1. What version of Python are you using? 3.11
1. What version of coverage.py shows the problem? 7.2.5
1. What code shows the problem?  See above 
1. What commands should we run to reproduce the problem?

pytest test_simple.py --cov=Simple

**Expected behavior**
I want to show 25% covered rather than 62%

**Additional context**
Thanks a lot for your package.  It's pretty helpful otherwise.

**Comment by nedbat** [comment]
Coverage.py doesn't have an option to count functions instead of lines.  Lines are more important because each line is a separate opportunity for a bug to occur, so you need to know which haven't been tested.

Overall, don't read too much meaning into the numbers themselves.  The only important thing about 62% is that it's better than 61% and not as good as 63%.
