### ISSUE TITLE
Coverage=5.3, the .coveragerc file for exclude lines contains @ will raise some problem

### ISSUE THREAD

**Issue by Chenyu-dev353** [coveragepy/coveragepy#1854]
```
from bootstrap import app
import time


@app.route('/home')
def home():
    return 'Hello, Flask!'


@app.route('/demo')
def demo():
    x = 1
    return str(x)


@app.route('/test')
def test():
    x = 1
    y = 2
    return str(x + y)

```

Above is my Python file views.py and I am trying to exclude some lines like decorators starting with @, this is the result without any request with .coveragerc file:

```
[report]
exclude_lines =
    pragma: no cover
    def __repr__
    if self\.debug
    raise AssertionError
    raise NotImplementedError
    if 0:
    if __name__ == .__main__.:
    ^import\s+
    ^from.*import.*

ignore_errors = True
fail_under = 0
skip_covered = False
sort = Cover

```

Name           Stmts   Miss  Cover   Missing
--------------------------------------------
**views.py           9      9     0%   5-20**

and after I simply add a '@' in the exclude_lines, the result turned out to be:

Name           Stmts   Miss  Cover   Missing
--------------------------------------------
**views.py           0      0   100%**

Even if I change it to ^@.* it still excluded everything

**Comment by nedbat** [comment]
Excluding a decorator line also excludes the function it is decorating.  You shouldn't try to remove these lines.  I don't know why you want to exclude import lines either.  I guess you are trying to limit the measurement to only the "real" lines of code, but that is not possible in Python, because all of these lines are actually executed.
