### ISSUE TITLE
Place optparse inside module

### ISSUE THREAD

**Issue by thechief389** [coveragepy/coveragepy#712]
Optparse is deprecated and may be removed from a future release, which can cause coverage to break.

To fix this, you can have a copy of optparse.py inside the module so that optparse will still be available even if optparse gets removed.

A better option would be to switch to [argparse](https://docs.python.org/3/library/argparse.html) or [click](https://click.palletsprojects.com/en/7.x/) but that would require changing the entire code for the cli and argparse has cosmetic issues with the help output for subcommands.

Click also has it's own [problems](https://www.reddit.com/r/Python/comments/73xb5y/click_reviews_should_i_migrate_to_click_from/dntuqlb).

**Comment by nedbat** [comment]
Thanks for thinking about this.  I won't vendor optparse, since it is still in the Python standard library.  Click is an external dependency, which I avoid in coverage.py.  I'll just leave the code as it is for now.  If they do remove optparse in  the future, we will have plenty of time to replace our use of it.
