### ISSUE TITLE
What context data can reside in coveragepy sqlite3 database?

### ISSUE THREAD

**Issue by fkromer** [coveragepy/coveragepy#734]
I ran tests over my project with coveragepy v5.03a and checked the resulting sqlite3 database (schema v2) content. There are some rows with context [`<empty>`](https://github.com/fkromer/python-tia/blob/master/lab/coveragepy_sqlite_interface.ipynb?short_path=84b7dc2#L84) and [`testsfailed`](https://github.com/fkromer/python-tia/blob/master/lab/coveragepy_sqlite_interface.ipynb?short_path=84b7dc2#L96) which I didn't expect. (I expected only tests in there.) Where are these rows coming from? Is there potentially other context data other than tests included in the database?

**Comment by nedbat** [comment]
Can you give me a way to reproduce it myself?

**Comment by fkromer** [comment]
It should be reproducible like this (depends on JupiterLab, pipenv and Python3.6):

    $ git clone https://github.com/fkromer/python-tia.git
    $ cd python-tia
    $ pipenv install --dev
    $ pipenv shell
    $ jupyter-lab

In the JupyterLab UI -> `<python-tia>/data/coveragepy_sqlite_interface.ipynb`. The code opens this [database](https://github.com/fkromer/python-tia/blob/master/tests/data/.coverage).

**Comment by nedbat** [comment]
(I meant how to run the tests, but you have a tox.ini, so that was easy!)

The empty string context is code that is run outside of any tests.  I'm not sure what "testsfailed" is from exactly, but you have no lines recorded for it.  It must be due to my simplistic check for a new context: function name begins with "test".

I expect to be working on a plugin for pytest to do a better job determining the contexts.

**Comment by fkromer** [comment]
First I had the notebooks only. I added the functionality and tests later. You recognized before I was able to inform you about that 😉
