### ISSUE TITLE
Travis CI/Mac: No module named 'coverage'

### ISSUE THREAD

**Issue by typeworld** [coveragepy/coveragepy#933]
Since a few days or weeks, I'm not sure when it started, my Mac tests on Travis CI are failing with:

```
coverage run ./Lib/typeWorld/test.py
Traceback (most recent call last):
  File "/Users/travis/venv/bin/coverage", line 5, in <module>
    from coverage.cmdline import main
ModuleNotFoundError: No module named 'coverage'
```

My build matrix includes Windows and Linux OSs, and only the Mac one fails with the above traceback. 
I'm not sure whether to report the issue here or there, so I started here ;)
Since it's Travis CI, I'm assuming that the latest coverage package version is installed. At least I haven't specified any specific version anywhere.

You can find the test run here, and restart yourself, I believe: https://travis-ci.org/typeworld/typeworld/jobs/651640312

Please let me know if I can assist with anything.

**Comment by nedbat** [comment]
I don't know why you would be getting that failure.  I can't think of anything that changed in coverage that would cause that.

Your .travis.yml file is very unusual: why install requirements with a separate pip command for each package? Why repeat that list three times in your yml file?  The linux clause uses a mix of pip and pip3, which seems wrong.

I would recommend creating a requirements.txt file, and install it with one pip command.  Since you are using coverage directly, I would also recommend installing it explicitly, rather than letting codecov pull it in as a dependency.
